### ISSUE TITLE
Account for Duplicate Entries

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/scrap-preprocessor#57] opened 2016-10-18 00:07 UTC
Some of the entries in our input csv files are duplicate. Search for those entries and remove them. 

Some of the points to remember:

1. This step should be performed before Google AutoComplete.
2. You might need to consider Name + Street Address + Locality to find duplicate entries.

**Comment by gupta-shantanu** [comment] 2016-10-23 18:06
@shashwat-vik can you please share your findings related to the issue?

**Comment by shashwat-vik** [comment] 2016-10-24 09:35
Yeah. Sure.

Whenever I use the term **Duplicates**, it will mean they have the same values for **'MAIN FIELDS'** and rest fields may or may not be same.
**'MAIN FIELDS'** are following columns: **['Name','Street Address','Locality','City','Pincode']**

The motivation for these fields is to uniquely pin-point an Institute, including cases when it may have multiple branches in same city.

So sometimes we get large number (in some cases 50%) of duplicates.
Now they can't be deleted straight away when we have some important columns (like emails,phone nos, working hours,etc) different for these duplicates.

Taking this into account we got two steps:
	

1. Deleting Rows
    - This can be safely done when the Duplicates are differeing only by EduID

2. Merging Row

   - For this it may depend on the columns the duplicates are differing by.
      If duplicates are differing either by 1 or all of the below, we can merge them safely:
		- Keywords
		- Main Category

      _(Will add more once I get more comparisons)_
	   

   - However it becomes little noisy when they differ by following:
		- Website
		- Phone [1-5]
		- Mail
		- Person to Contact
		- Working Hours

      Now this has two scenarios. 
      **A.** When the cause of difference is because one row has data while the other was None. So this will also come under the case of safe merging.
      **B.** When the data is different. That needs to be figured out examining the case so that accuracy is not hurt. So we can consider certain column combinations.

I am still testing to get count of cases when rows can be safely merged.

Meanwhile checkout the reports I generated per file from "**_scrap-preprocessor/input_**" at the bottom links, which I am using for analysis 

They data in each file carries the same definition of Duplicates I defined here.
The data listed there is like this:
		_**row_no_x --> row_no_y**_

This means **_row_no_x_** and **_row_no_y_** are duplicates.
And just below that you will see the names of differing columns for these duplicates.
		
[vijayawada_output_1.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547347/vijayawada_output_1.txt)
[nagpur_output_1.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547348/nagpur_output_1.txt)
[sample.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547349/sample.txt)
[sample_big.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547350/sample_big.txt)
[scrap_rajkot_output_1.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547351/scrap_rajkot_output_1.txt)
[scrap_thrissur_output_1.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547352/scrap_thrissur_output_1.txt)
[scrap_visakhapatnam.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547353/scrap_visakhapatnam.txt)
[scrap4_mumbai.txt](https://github.com/rohitmanglik/scrap-preprocessor/files/547354/scrap4_mumbai.txt)

**Comment by shashwat-vik** [comment] 2016-10-25 22:39
Ensured safety in Autocomplete and FB prediction analysis through the commit 831befe2b7dfb57f74439c6c84d4db4fcdc6c743 due to the consequences of merging rows.

**Closed by shashwat-vik** 2016-10-25 22:39 UTC
